name: Zizmor

on:
  push:
    branches: [main, master]
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
  pull_request:
    branches: [main, master]
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
  workflow_dispatch:

permissions: {}

concurrency:
  group: zizmor-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  zizmor:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      actions: read
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@192e21d79ab29983730a13d1382995c2307fbcaa # v0.5.7
        with:
          advanced-security: false
          annotations: true
          min-severity: medium
          version: v1.25.2
